version: 2

jobs:
  # using tox
  toxify:
      docker:
        - image: python:2.7
      environment:
        TOXENV: py27
      steps: &toxsteps
        - checkout
        - run:
            name: Install utils
            command: |
              pip install tox wheel
        - run:
            command: tox -e py27

workflows:
  version: 2

  build:
    jobs:
      - toxify
